baseURL = '/'
relativeURLs = true
languageCode = 'en-us'
title = '🚀 Bintang Pradana Erlangga Putra'
theme = 'archie'
copyright = '© Bintang Pradana Erlangga Putra'

paginate=5

[params]
mode="auto" # color-mode → light,dark,toggle or auto
useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
subtitle = "Random thoughts and notes from a bored software engineer."
mathjax = true # enable MathJax support
katex = true # enable KaTeX support


# Social

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/bintang_pradana/"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://gitlab.com/bpradana/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/bpradana"


# Menus

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
