name: Deploy

on:
  push:
    branches:
      - master
      - main

jobs:
  build-upload:
    runs-on: ubuntu-latest
    name: Build and upload Docker image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.REGISTRY_HOST }}/${{ secrets.USERNAME }}/site:latest

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to VPS
    needs: build-upload

    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.REGISTRY_HOST }}/${{ secrets.USERNAME }}/site:latest
            docker stop site || true
            docker rm site || true
            docker run -d --name site -p 80:80 ${{ secrets.REGISTRY_HOST }}/${{ secrets.USERNAME }}/site:latest
